/**
 * Feature: qr-restaurant-system, Property 16: User creation required fields
 * Validates: Requirements 4.1
 * 
 * Property: For any user creation attempt without email, password, or role, the system should reject the creation
 */

import * as fc from 'fast-check';
import { validateUserCreation } from '../utils/validation';

describe('Property 16: User creation required fields', () => {
  it('should reject user creation without email', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 8 }),
        fc.constantFrom('admin', 'waiter', 'chef'),
        (password, role) => {
          const result = validateUserCreation({
            email: '',
            password,
            role,
          });

          expect(result.success).toBe(false);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should reject user creation without password', () => {
    fc.assert(
      fc.property(
        fc.emailAddress(),
        fc.constantFrom('admin', 'waiter', 'chef'),
        (email, role) => {
          const result = validateUserCreation({
            email,
            password: '',
            role,
          });

          expect(result.success).toBe(false);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should reject user creation without role', () => {
    fc.assert(
      fc.property(fc.emailAddress(), fc.string({ minLength: 8 }), (email, password) => {
        const result = validateUserCreation({
          email,
          password,
          role: '',
        });

        expect(result.success).toBe(false);
      }),
      { numRuns: 100 }
    );
  });

  it('should accept user creation with all required fields', () => {
    fc.assert(
      fc.property(
        fc.emailAddress(),
        fc.stringMatching(/^[a-zA-Z0-9!@#$%^&*]{8,50}$/),
        fc.constantFrom('admin', 'waiter', 'chef'),
        (email, password, role) => {
          const result = validateUserCreation({
            email,
            password,
            role,
          });

          // If validation fails, it should be due to invalid email format
          if (!result.success) {
            // Skip invalid emails generated by fc.emailAddress()
            fc.pre(false);
          }

          expect(result.success).toBe(true);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should reject user creation with invalid email format', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 1 }).filter((s) => !s.includes('@')),
        fc.string({ minLength: 8 }),
        fc.constantFrom('admin', 'waiter', 'chef'),
        (invalidEmail, password, role) => {
          const result = validateUserCreation({
            email: invalidEmail,
            password,
            role,
          });

          expect(result.success).toBe(false);
        }
      ),
      { numRuns: 100 }
    );
  });
});


/**
 * Feature: qr-restaurant-system, Property 20: Password length validation
 * Validates: Requirements 4.5
 * 
 * Property: For any password update with length less than 8 characters, the system should reject it;
 * for any password with 8 or more characters, the system should accept it
 */

describe('Property 20: Password length validation', () => {
  it('should reject passwords shorter than 8 characters', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 0, maxLength: 7 }).filter((s) => s.trim().length < 8),
        (shortPassword) => {
          const result = validateUserCreation({
            email: 'test@example.com',
            password: shortPassword,
            role: 'waiter',
          });

          expect(result.success).toBe(false);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should accept passwords with 8 or more characters', () => {
    fc.assert(
      fc.property(
        fc.stringMatching(/^[a-zA-Z0-9!@#$%^&*]{8,50}$/),
        (validPassword) => {
          const result = validateUserCreation({
            email: 'test@example.com',
            password: validPassword,
            role: 'waiter',
          });

          expect(result.success).toBe(true);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should reject passwords with only whitespace even if 8+ chars', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 8, max: 20 }),
        (length) => {
          const whitespacePassword = ' '.repeat(length);
          
          const result = validateUserCreation({
            email: 'test@example.com',
            password: whitespacePassword,
            role: 'waiter',
          });

          expect(result.success).toBe(false);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should accept passwords with mixed content and 8+ non-whitespace chars', () => {
    fc.assert(
      fc.property(
        fc.stringMatching(/^[a-zA-Z0-9!@#$%^&*]{8,}$/),
        (password) => {
          const result = validateUserCreation({
            email: 'test@example.com',
            password,
            role: 'waiter',
          });

          expect(result.success).toBe(true);
        }
      ),
      { numRuns: 100 }
    );
  });
});
